### ISSUE TITLE
What kind of license does your project have?

### ISSUE THREAD

**Issue by egslava** [jess-anders/two-way-gridview#14]
Hi!
I have a library for working with lists (network data loading, pagination, etc) so with standard list it supports your two-way-grid-view library for horizontal lists. 

But I didn't find any information about license of this project :( So, what kind of license does your project use?

**Comment by dandar3** [comment]
I believe it says it on the main page:
https://github.com/jess-anders/two-way-gridview

_Feel free to use it in your apps, according to the Apache 2.0 license. Also feel free to fork it and improve it. You could fairly easily create a horizontal listview by extending TwoWayAbsListView_

**Comment by egslava** [comment]
Wow, sorry, I haven't noticed that :(

**Comment by dandar3** [comment]
No need, we all miss things at times :-)
