### ISSUE TITLE
Gridview with one column when it should be with 5 columns.

### ISSUE THREAD

**Issue by RafaCoimbra** [jess-anders/two-way-gridview#4]
I'm using Gridview Two Way, and he is getting only one column when it should fill an entire row and scroll horizontally.

I need to mandatorily use the Adapter Two Way or can I use my own adapter?

**Comment by jess-anders** [comment]
You can use your own adapter.  If you have it configured to scroll horizontally, then the column width is controlled by each item's width.  Just like in a vertically scrolling ListView, each item's height is controlled by the item itself.
